EmotionRecognitionSite/EmotionRecognitionSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recognition/', include('recognition.urls')),
    path('', RedirectView.as_view(url='/recognition/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmotionRecognitionSite/recognition/urls.py
from django.urls import path

from .views import home, register, user_login, user_logout, dashboard, add_image_feed, add_video_feed, \
    process_image_feed, process_video_feed, delete_image, delete_video

from django.conf import settings
from django.conf.urls.static import static

app_name = 'recognition'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('process/<int:feed_id>/', process_image_feed, name='process_feed'),
    path('process_video/<int:feed_video_id>/', process_video_feed, name='process_video_feed'),
    path('add-image-feed/', add_image_feed, name='add_image_feed'),
    path('add-video-feed/', add_video_feed, name='add_video_feed'),
    path('image/delete/<int:image_id>/', delete_image, name='delete_image'),
    path('video/delete/<int:video_id>/', delete_video, name='delete_video'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmotionRecognitionSite/recognition/models.py
from django.db import models
from django.conf import settings


class ImageFeed(models.Model):
    image = models.ImageField(upload_to='images/')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.image.name}"


class RecognizedEmotion(models.Model):
    confidence = models.FloatField(null=True)
    emotion = models.CharField(max_length=30, null=True)
    info_feed = models.ForeignKey(ImageFeed, related_name='recognized_emotions', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.emotion} ({self.confidence}) on {self.info_feed.image.name}"


class VideoFeed(models.Model):
    video = models.FileField(upload_to='videos/')
    processed_video = models.FileField(upload_to='videos/', null=True, blank=True)
    graph_emotion = models.ImageField(upload_to='graph/', null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.video.name} - {self.processed_video}"

EmotionRecognitionSite/recognition/forms.py
from django import forms
from .models import ImageFeed, VideoFeed


class ImageFeedForm(forms.ModelForm):
    class Meta:
        model = ImageFeed
        fields = ['image']
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'}),
        }
        help_texts = {
            'image': 'Upload an image file.',
        }


class VideoFeedForm(forms.ModelForm):
    class Meta:
        model = VideoFeed
        fields = ['video']
        widgets = {
            'video': forms.FileInput(attrs={'accept': 'video/*'}),
        }
        help_texts = {
            'video': 'Upload an videos file.',
        }

EmotionRecognitionSite/recognition/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from torch.distributed.autograd import context

from .forms import ImageFeedForm, VideoFeedForm
from .models import ImageFeed, VideoFeed
from .utils import process_image, process_video


def home(request):
    return render(request, 'recognition/home.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('recognition:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'recognition/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('recognition:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'recognition/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('recognition:login')


@login_required
def dashboard(request):
    image_feeds = ImageFeed.objects.filter(user=request.user)
    video_feeds = VideoFeed.objects.filter(user=request.user)
    context = {
        'image_feeds': image_feeds,
        'video_feeds': video_feeds
    }
    return render(request, 'recognition/dashboard.html', context)


@login_required
def add_image_feed(request):
    if request.method == 'POST':
        form = ImageFeedForm(request.POST, request.FILES)
        if form.is_valid():
            image_feed = form.save(commit=False)
            image_feed.user = request.user
            image_feed.save()
            return redirect('recognition:dashboard')
    else:
        form = ImageFeedForm()
    return render(request, 'recognition/add_image_feed.html', {'form': form})


@login_required
def add_video_feed(request):
    if request.method == 'POST':
        form = VideoFeedForm(request.POST, request.FILES)
        if form.is_valid():
            video_feed = form.save(commit=False)
            video_feed.user = request.user
            video_feed.save()
            return redirect('recognition:dashboard')
    else:
        form = VideoFeedForm()
    return render(request, 'recognition/add_video_feed.html', {'form': form})


@login_required
def process_image_feed(request, feed_id):
    image_feed = get_object_or_404(ImageFeed, id=feed_id, user=request.user)
    process_image(feed_id)
    return redirect('recognition:dashboard')


@login_required
def process_video_feed(request, feed_video_id):
    video_feed = get_object_or_404(VideoFeed, id=feed_video_id, user=request.user)
    process_video(feed_video_id)
    return redirect('recognition:dashboard')


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(ImageFeed, id=image_id, user=request.user)                                     # Ensuring only the owner can delete
    image.delete()
    return redirect('recognition:dashboard')


@login_required
def delete_video(request, video_id):
    video = get_object_or_404(VideoFeed, id=video_id, user=request.user)                                     # Ensuring only the owner can delete
    video.delete()
    return redirect('recognition:dashboard')

EmotionRecognitionSite/recognition/templates/recognition/add_image_feed.html
{% extends "recognition/base.html" %}

{% block content %}
<h2>Add Image Feed</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload Image</button>
</form>
{% endblock %}

EmotionRecognitionSite/recognition/templates/recognition/add_video_feed.html
{% extends "recognition/base.html" %}

{% block content %}
<h2>Add Video Feed</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload Video</button>
</form>
{% endblock %}

EmotionRecognitionSite/recognition/templates/recognition/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Emotion Recognition Platform{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href='{% static "style.css" %}'>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <a class="navbar-brand" href="{% url 'recognition:home' %}">Emotion Recognition Platform</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'recognition:home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recognition:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recognition:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recognition:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recognition:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

EmotionRecognitionSite/recognition/templates/recognition/dashboard.html
{% extends "recognition/base.html" %}

{% block content %}
<h2>Dashboard</h2>
<a href="{% url 'recognition:add_image_feed' %}" class="btn btn-primary mb-3">Add Image</a>
<a href="{% url 'recognition:add_video_feed' %}" class="btn btn-primary mb-3">Add Video</a>

{% for feed in image_feeds %}
    <div class="card mb-3">
        <div class="card-header">
            <a href="{% url 'recognition:process_feed' feed.id %}" class="btn btn-secondary">Process Image</a>
        </div>
        <div class="card-body">
            <a href="{{ feed.image.url }}" target="_blank">
                <img src="{{ feed.image.url }}" alt="Original Image" style="width: 320px; height: 240px;">
            </a>
            <ul>
                {% for obj in feed.recognized_emotions.all %}
                    <li>{{ obj.emotion }} - {{ obj.confidence|floatformat:2 }}</li>
                {% endfor %}
            </ul>
        </div>
        <form action="{% url 'recognition:delete_image' feed.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endfor %}


{% for feed_v in video_feeds %}
    <div class="card mb-3">
        <div class="card-header">
            <a href="{% url 'recognition:process_video_feed' feed_v.id %}" class="btn btn-secondary">Process Video</a>
        </div>
        <div class="card-body">
            <a href="{{ feed_v.video.url }}" target="_blank">
                <video width="320" height="240" controls>
                    <source src="{{ feed_v.video.url }}">
                </video>
            </a>
            {% if feed_v.processed_video %}
            <a href="{{ feed_v.processed_video.url }}" target="_blank">
                <video width="320" height="240" controls>
                    <source src="{{ feed_v.processed_video.url }}">
                </video>
            </a>
            {% endif %}
            {% if feed_v.graph_emotion %}
            <div class="card-body">
                <a href="{{ feed_v.graph_emotion.url }}" target="_blank">
                    <img src="{{ feed_v.graph_emotion.url }}" alt="Graph of emotions" style="width: 75px; height: 75px;">
                </a>
            </div>
            {% endif %}
        <form action="{% url 'recognition:delete_video' feed_v.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
        </div>
    </div>
{% endfor %}
{% endblock %}

EmotionRecognitionSite/recognition/templates/recognition/home.html
{% extends "recognition/base.html" %}

{% block content %}
<h1>Welcome to the Emotion Recognition Platform</h1>
<p>This is the home page of your application.</p>
<a href="{% url 'recognition:dashboard' %}">Go to Dashboard</a>
{% endblock %}

EmotionRecognitionSite/recognition/templates/recognition/login.html
{% extends "recognition/base.html" %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

EmotionRecognitionSite/recognition/templates/recognition/register.html
{% extends "recognition/base.html" %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}